name: miuivs_patch_build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Services.jar URL'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up
        run: |
          sudo apt-get install -y git wget zip unzip axel python3-pip zipalign apksigner xmlstarlet
          pip3 install ConfigObj

      - name: Set up Time
        run: |
          echo "Setting Indian timezone"
          sudo timedatectl set-timezone Asia/Kolkata

      - name: Download Services.jar
        run: |
          axel -n $(nproc) "${{ github.event.inputs.ROM_URL }}"

      - name: PATCH-ING
        run: |
          sudo chmod -R 777 .
          ./bhlnk.sh

      - name: Upload Patched Services.jar
        uses: actions/upload-artifact@v3
        with:
          name: services_patched_bhlnk
          path: ./module/*
          if-no-files-found: error
          
